/**
 * ShaftScene.tsx - Interactive 3D elevator shaft viewer
 *
 * Renders the elevator shaft model using React Three Fiber with:
 * - OBJ/MTL model loading with material management
 * - Click-to-select components with condition-based highlighting
 * - Hover effects with pointer cursor change
 * - Floating HTML labels on each component (drei Html)
 * - Hover tooltip showing name + condition
 * - Camera animation that focuses on the selected component
 * - Theme-aware lighting, environment, and colors
 * - OrbitControls for user navigation (pan, zoom, rotate)
 */

import { Canvas, ThreeEvent, useFrame } from '@react-three/fiber';
import { OrbitControls, Environment, ContactShadows, Html } from '@react-three/drei';
import { useEffect, useState, useRef } from 'react';
import * as THREE from 'three';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
import { MTLLoader } from 'three/examples/jsm/loaders/MTLLoader.js';
import type { Component } from '../../shared/types';

interface Props {
  onSelect: (c: Component) => void;
  selected: Component | null;
  theme?: 'dark' | 'light';
  components?: Component[];
}

// Highlight colors mapped to component condition
const conditionColors: Record<string, number> = {
  good: 0x22c55e,
  fair: 0xf59e0b,
  poor: 0xef4444,
};

// CSS color strings for HTML overlays
const conditionCssColors: Record<string, string> = {
  good: '#22c55e',
  fair: '#f59e0b',
  poor: '#ef4444',
};

/**
 * Approximate 3D world positions for each component.
 * Used for label placement, camera focus targets, and tooltip positioning.
 * These correspond to the OBJ model geometry generated by scripts/generate-model.mjs.
 */
const componentPositions: Record<string, [number, number, number]> = {
  'Door_L1': [0, 1.1, 1.5],
  'Door_L6': [0, 16.1, 1.5],
  'GuideRail_Left': [-1.5, 10, 0.5],
  'GuideRail_Right': [1.5, 10, 0.5],
  'Car': [0, 7.5, 1.2],
  'Cable_Main': [0.4, 15, 0.5],
};

// Non-interactive structural objects (shaft walls, floor slabs)
const structuralObjects = new Set(['Shaft_Structure']);

/**
 * ShaftModel - Loads and renders the OBJ model with interactive highlighting.
 * Manages original materials, hover state, and selection highlighting.
 */
function ShaftModel({ onSelect, selected, onHover }: Props & { onHover: (comp: Component | null) => void }) {
  const [scene, setScene] = useState<THREE.Group | null>(null);
  const [components, setComponents] = useState<Component[]>([]);
  const [hovered, setHovered] = useState<string | null>(null);
  const originalMaterials = useRef<Map<string, THREE.Material | THREE.Material[]>>(new Map());

  // Fetch component data to map mesh names to component info
  useEffect(() => {
    fetch('/api/shafts/1')
      .then((r) => r.json())
      .then((data) => setComponents(data.components));
  }, []);

  // Load OBJ + MTL model and store original materials for reset
  useEffect(() => {
    const mtlLoader = new MTLLoader();
    mtlLoader.setPath('/models/');
    mtlLoader.load('shaft.mtl', (materials) => {
      materials.preload();
      const objLoader = new OBJLoader();
      objLoader.setMaterials(materials);
      objLoader.setPath('/models/');
      objLoader.load('shaft.obj', (obj) => {
        obj.traverse((child) => {
          if (child instanceof THREE.Mesh) {
            const name = child.parent?.name || child.name;
            originalMaterials.current.set(name, child.material);
            // Make shaft walls semi-transparent so internals are visible
            if (structuralObjects.has(name)) {
              child.material = new THREE.MeshStandardMaterial({
                color: 0x1a2035,
                transparent: true,
                opacity: 0.6,
                metalness: 0.3,
                roughness: 0.8,
                side: THREE.DoubleSide,
              });
            }
          }
        });
        setScene(obj);
      });
    });
  }, []);

  // Apply highlight materials based on selection/hover state
  useEffect(() => {
    if (!scene) return;
    scene.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        const objName = child.parent?.name || child.name;
        if (structuralObjects.has(objName)) return;

        const comp = components.find((c) => c.mesh_name === objName);

        if (selected?.mesh_name === objName) {
          // Selected: glow with condition color
          const condColor = conditionColors[selected.condition] || 0x3b82f6;
          child.material = new THREE.MeshStandardMaterial({
            color: condColor,
            emissive: condColor,
            emissiveIntensity: 0.35,
            metalness: 0.6,
            roughness: 0.25,
          });
        } else if (hovered === objName && comp) {
          // Hovered: subtle blue highlight
          child.material = new THREE.MeshStandardMaterial({
            color: 0x60a5fa,
            emissive: 0x3b82f6,
            emissiveIntensity: 0.15,
            metalness: 0.5,
            roughness: 0.35,
          });
        } else {
          // Default: restore original material
          const orig = originalMaterials.current.get(objName);
          if (orig) child.material = orig as THREE.Material;
        }
      }
    });
  }, [selected, hovered, scene, components]);

  // Click handler — select the clicked component
  const handleClick = (e: ThreeEvent<MouseEvent>) => {
    e.stopPropagation();
    const objName = e.object.parent?.name || e.object.name;
    if (structuralObjects.has(objName)) return;
    const comp = components.find((c) => c.mesh_name === objName);
    if (comp) onSelect(comp);
  };

  // Hover enter — highlight component and show tooltip
  const handlePointerOver = (e: ThreeEvent<PointerEvent>) => {
    e.stopPropagation();
    const objName = e.object.parent?.name || e.object.name;
    if (structuralObjects.has(objName)) return;
    const comp = components.find((c) => c.mesh_name === objName);
    if (comp) {
      setHovered(objName);
      onHover(comp);
      document.body.style.cursor = 'pointer';
    }
  };

  // Hover exit — clear highlight and tooltip
  const handlePointerOut = () => {
    setHovered(null);
    onHover(null);
    document.body.style.cursor = 'default';
  };

  if (!scene) return null;
  return (
    <primitive
      object={scene}
      onClick={handleClick}
      onPointerOver={handlePointerOver}
      onPointerOut={handlePointerOut}
    />
  );
}

/**
 * ComponentLabels - Renders floating HTML labels in 3D space for each component.
 * Labels show component name with a condition-colored left border.
 * Selected component label is highlighted in blue.
 */
function ComponentLabels({ components, selected }: { components: Component[]; selected: Component | null }) {
  return (
    <>
      {components.map((comp) => {
        const pos = componentPositions[comp.mesh_name ?? ''];
        if (!pos) return null;
        const isSelected = selected?.id === comp.id;
        return (
          <Html
            key={comp.id}
            position={pos}
            center
            distanceFactor={12}
            style={{ pointerEvents: 'none' }}
          >
            <div
              style={{
                background: isSelected ? 'rgba(59,130,246,0.9)' : 'rgba(15,21,33,0.85)',
                color: '#f1f5f9',
                padding: '3px 8px',
                borderRadius: '4px',
                fontSize: '10px',
                fontFamily: 'Inter, sans-serif',
                fontWeight: isSelected ? 600 : 400,
                whiteSpace: 'nowrap',
                border: `1px solid ${isSelected ? '#3b82f6' : 'rgba(255,255,255,0.1)'}`,
                borderLeft: `3px solid ${conditionCssColors[comp.condition] ?? '#64748b'}`,
                transform: 'translateY(-20px)',
                opacity: 0.9,
              }}
            >
              {comp.name}
            </div>
          </Html>
        );
      })}
    </>
  );
}

/**
 * HoverTooltip - Shows a floating tooltip above the hovered component
 * with condition dot, name, and condition text.
 */
function HoverTooltip({ hovered }: { hovered: Component | null }) {
  if (!hovered) return null;
  const pos = componentPositions[hovered.mesh_name ?? ''];
  if (!pos) return null;

  return (
    <Html position={[pos[0], pos[1] + 1.5, pos[2]]} center style={{ pointerEvents: 'none' }}>
      <div
        style={{
          background: 'rgba(15,21,33,0.95)',
          color: '#f1f5f9',
          padding: '8px 12px',
          borderRadius: '8px',
          fontSize: '12px',
          fontFamily: 'Inter, sans-serif',
          whiteSpace: 'nowrap',
          border: '1px solid rgba(255,255,255,0.1)',
          boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
        }}
      >
        <span
          style={{
            width: '8px',
            height: '8px',
            borderRadius: '50%',
            background: conditionCssColors[hovered.condition],
            boxShadow: `0 0 6px ${conditionCssColors[hovered.condition]}`,
          }}
        />
        <span style={{ fontWeight: 600 }}>{hovered.name}</span>
        <span style={{ color: conditionCssColors[hovered.condition], fontWeight: 500, textTransform: 'capitalize' }}>
          {hovered.condition}
        </span>
      </div>
    </Html>
  );
}

/**
 * CameraController - Smoothly animates the orbit target to focus on the selected component.
 * When nothing is selected, centers on the shaft midpoint.
 * Uses lerp for smooth transitions rather than instant jumps.
 */
function CameraController({ selected }: { selected: Component | null }) {
  const controlsRef = useRef<any>(null);
  const targetLookAt = useRef(new THREE.Vector3(0, 9, 0));

  // Update target position when selection changes
  useEffect(() => {
    if (selected?.mesh_name && componentPositions[selected.mesh_name]) {
      const [x, y, z] = componentPositions[selected.mesh_name];
      targetLookAt.current.set(x, y, z);
    } else {
      targetLookAt.current.set(0, 9, 0); // Default: shaft center
    }
  }, [selected]);

  // Smoothly interpolate orbit target each frame
  useFrame(() => {
    if (controlsRef.current) {
      controlsRef.current.target.lerp(targetLookAt.current, 0.04);
      controlsRef.current.update();
    }
  });

  return (
    <OrbitControls
      ref={controlsRef}
      target={[0, 9, 0]}
      enableDamping
      dampingFactor={0.08}
      minDistance={3}
      maxDistance={50}
      minPolarAngle={0.1}
      maxPolarAngle={Math.PI / 2}
    />
  );
}

/**
 * ShaftScene - Main exported component that sets up the Three.js canvas.
 * Configures lighting, environment, fog, and ground based on the active theme.
 */
export default function ShaftScene({ onSelect, selected, theme = 'dark', components = [] }: Props) {
  const [hoveredComp, setHoveredComp] = useState<Component | null>(null);

  // Theme-dependent visual parameters
  const isDark = theme === 'dark';
  const sceneBg = isDark ? '#0a0e1a' : '#e8ecf2';
  const groundColor = isDark ? '#0f1521' : '#d1d9e6';
  const fogColor = isDark ? '#0a0e1a' : '#e8ecf2';
  const ambientIntensity = isDark ? 0.4 : 0.7;
  const envPreset = isDark ? 'night' : 'city';

  return (
    <Canvas
      camera={{ position: [10, 12, 20], fov: 50 }}
      shadows
      gl={{ antialias: true, toneMapping: THREE.ACESFilmicToneMapping, toneMappingExposure: isDark ? 1.0 : 1.3 }}
      style={{ background: sceneBg }}
    >
      {/* Three-point lighting setup */}
      <ambientLight intensity={ambientIntensity} />
      <directionalLight
        position={[8, 20, 10]}
        intensity={isDark ? 1.2 : 1.8}
        castShadow
        shadow-mapSize={[1024, 1024]}
      />
      <directionalLight position={[-5, 12, -3]} intensity={isDark ? 0.3 : 0.5} color={isDark ? '#94a3b8' : '#bfdbfe'} />
      <pointLight position={[0, 9, 3]} intensity={isDark ? 0.6 : 0.4} color="#e2e8f0" distance={15} />

      {/* HDRI environment for realistic reflections */}
      <Environment preset={envPreset} background={false} />

      {/* Depth fog to fade distant geometry */}
      <fog attach="fog" args={[fogColor, 20, 55]} />

      {/* Interactive 3D model */}
      <ShaftModel onSelect={onSelect} selected={selected} onHover={setHoveredComp} />

      {/* Floating labels on each component */}
      <ComponentLabels components={components} selected={selected} />

      {/* Tooltip shown on hover */}
      <HoverTooltip hovered={hoveredComp} />

      {/* Ground plane */}
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.2, 0]} receiveShadow>
        <planeGeometry args={[40, 40]} />
        <meshStandardMaterial color={groundColor} roughness={0.9} metalness={0.1} />
      </mesh>

      {/* Contact shadows for visual grounding */}
      <ContactShadows
        position={[0, -0.19, 0]}
        opacity={isDark ? 0.5 : 0.3}
        scale={15}
        blur={2.5}
        far={12}
      />

      {/* Camera controls with animated focus */}
      <CameraController selected={selected} />
    </Canvas>
  );
}
